export default {
  primary: '#0073B6',
  primaryFg1: 'white',
  primaryFg2: 'black',
  primaryBrightBlue: '#0073b6',
  primaryDisabled: 'gray',
  primaryDisabledLight: 'lightgray',
  primaryDisabledDark: 'darkgray',
  borderColor1: 'lightgray',
  borderColor2: 'rgba(151,151,151,0.5)',
  phase3BackgroundColor: 'lightgray',
  phase3Color: '#0073b6',
  phase2Color: '#fcf753',
  phase2BackgroundColor: 'lightgray',
  phase1Color: 'red',
  phase1BackgroundColor: 'lightgray',
  motorStatusOnbutton: 'green',
  motorStatusOffButton: 'red',

  validationIconError: '#ad3d3c',
  validationIconSuccess: 'green',
  buttons: {
    borderColor: 'lightgray',
  },
  progressIndicator: '#0073B6',
};
